# Generated by Django 5.2.7 on 2025-11-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
