# Generated by Django 5.2.7 on 2025-11-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_lead_lead_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Leads',
        ),
    ]
