# Generated by Django 5.2.7 on 2025-11-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_lead_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('sales_offer_details', models.TextField()),
                ('nurturing_channel', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leads', models.ManyToManyField(related_name='campaigns', to='crm.leads')),
            ],
        ),
    ]
