# Generated by Django 5.2.7 on 2025-11-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_conversation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_conversation_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
